In [1]:
import numpy as np


# Basic Numpy


In [2]:
a=np.array([1,2,3])
a


array([1, 2, 3])

In [3]:
b=np.array([[1.0,4.0,8.0],[3.0,6.0,5.0]])
b

array([[1., 4., 8.],
       [3., 6., 5.]])

In [4]:
#Get the dimension
a.ndim

1

In [5]:
b.ndim

2

In [6]:
#Get the shape 
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [9]:
#Get the type
a.dtype

dtype('int32')

In [10]:
b.dtype

dtype('float64')

In [12]:
#Get the size
a.itemsize

4

In [15]:
# Get the  total size
a.nbytes

12

In [16]:
b.nbytes

48

# Accessing/ changing specefic rows columns etc.

In [17]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [18]:
#get the specefic elements [r,c]
a[1,5]

13

In [20]:
#Get aspecefic row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
#Get a specefic column
a[:, 2]

array([ 3, 10])

In [23]:
#Getting a littlemore fancy  [startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [24]:
#changing something
a[1,5]=40
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 40, 14]])

In [26]:
a[:,2]=[1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 40, 14]])

### 3d example

In [27]:
b=([[[1,2],[3,4],[5,6],[7,8]]])
b

[[[1, 2], [3, 4], [5, 6], [7, 8]]]

In [28]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
# Get specific element (work outside in)
b[0,1,1]

4

# Initializing different types of arrays




In [33]:
# All 0s maytrix
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [35]:

# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [36]:

# Random decimal numbers
np.random.rand(4,2)

array([[0.69847139, 0.39182245],
       [0.82523105, 0.8533687 ],
       [0.43203827, 0.40462422],
       [0.187993  , 0.70173579]])

In [37]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 1, -3, -3],
       [ 1, -2, -3],
       [ 7, -3, -1]])

In [38]:

# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [40]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [41]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


# Mathematics

In [42]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [43]:
a + 2

array([3, 4, 5, 6])

In [44]:
a - 2

array([-1,  0,  1,  2])

In [45]:
a * 2

array([2, 4, 6, 8])

In [46]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [47]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [48]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [49]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [51]:
# To get more (https://docs.scipy.org/doc/numpy/reference/routines.math.html) 
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear Algebra

In [52]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [53]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [54]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse


# Stastistics

In [59]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
np.min(stats)

1

In [57]:
np.max(stats, axis=1)

array([3, 6])

In [58]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganizing Arrays

In [60]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [61]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:

# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])